[tool.poetry]
name = "sofwaredesign"
version = "0.1.0"
description = ""
authors = ["Florencia Silvestre <fsilvestre@pulsepoint.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
